json.id all_users.collect(&:id)
json.email all_users.collect(&:email)
# json.name all_users.collect(&:name)
# json.admin all_users.collect(&:admin)
json.accounts all_users.collect(&:accounts)
# json.avatar_url gravatar_image_url(current_resource_owner.email, size: 40)